import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import { cn } from "@/lib/utils";
import "./globals.css";

const roboto = Roboto({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, "antialiased min-h-screen")}>
        {children}
      </body>
    </html>
  );
}
